# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_snack_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='lastPurchaseDate',
            field=models.TextField(default='Never Purchased', null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='purchaseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snack',
            name='purchaseLocations',
            field=models.TextField(default='None Listed'),
        ),
    ]
